version: '3.8'

services:
    php:
        image: php:8.4-fpm
        container_name: symfony_php
        volumes:
            - ./BackEnd:/var/www/html
        depends_on:
            - db
        environment:
            DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - "8080:80"
        volumes:
            - ./BackEnd:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:17-alpine
        container_name: symfony_db
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
            POSTGRES_DB: symfony
        ports:
            - "5454:5432"
        volumes:
            - db_data:/var/lib/postgresql/data


volumes:
    db_data:


